# 1. Description
### Usage of Joblib and Pickle
#### Saving the trained Models:
* After training a machine learning model, you can save the model to disk. This allows you to load the model later and use it for making predictions without retraining.
* Save the trained machine learning model for future use.
* Training **machine learning model** can be quite time consuming if training dataset is very big. In this case it makes sense to **train a model and save it to a file** so that later on while making **predictions** you can just load that model from a file and you **don't need to train** it every time.
* **Pickle and sklearn's joblib modules** can be used for this purpose.
* **Joblib** seems to be more efficient with big **numpy arrays** hence it is preferred when you have many **numpy** objects involved in your training step.


# 2. Import libraries

In [ ]:
# import necessary required libraries
import pandas as pd
import numpy as np
from sklearn import linear_model

# 3. Load dataset

In [ ]:
# load the raw dataset from the csv file
url = "https://raw.githubusercontent.com/akdubey2k/ML/main/ML_5_Save_Model_Using_Joblib_And_Pickle/ML_5_homeprices_Save_Model_Using_Joblib_And_Pickle.csv"
df = pd.read_csv(url)
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

# 4. Data preprocessing

In [ ]:
# independent variable
X = df.drop('price',axis='columns')
X.head()

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [ ]:
# dependent variable
y = df.price
y.head()

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

# 5. Create and train the model

In [ ]:
lr_model = linear_model.LinearRegression()
# independent variable, dependent variable
# lr_model.fit(df[['area']], df.price)
lr_model.fit(X,y)

LinearRegression()

# 6. Validate the model

### predict the price of home with 5000 sq. ft. from trained model

In [ ]:
lr_model.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [ ]:
coef = lr_model.coef_

In [ ]:
inter = lr_model.intercept_

### Using linear regression to predict the house price
dependent variable = slope/coefficient * independent variable + intercept<br>
**y = m * X + b**

In [ ]:
# 135.78767123 * 5000 + 180616.43835616432
coef * 5000 + inter

array([859554.79452055])

# 7. Evaluate the model

In [ ]:
# lr_model.score(df[['area']], df['price'])
lr_model.score(X,y)

0.9584301138199486

# 8. Save Model To a File Using Python Pickle.
**Pickle** is a module in Python used for **_serializing and de-serializing_** Python objects.
* **Pickle** converts Python objects like **lists, dictionaries, etc. into byte streams (zeroes and ones).**
* The byte streams can be convert back into Python objects through a process called **unpickling.**
* The **pickle module** implements **binary protocols** for **_serializing and de-serializing_** a Python object structure.
* **“Pickling”** is the process whereby a <u>_Python object hierarchy is converted into a byte stream,_</u>
* **“unpickling”** is the <u>_inverse operation, whereby a byte stream (from a binary file or bytes-like object) is converted back into an object hierarchy._</u>
* **Pickling (and unpickling)** is alternatively known as **“serialization”, “marshalling,” or “flattening”;** however, to avoid confusion, the terms used here are **“pickling” and “unpickling”.**

## 8.1 Import pickle library

In [ ]:
import pickle

## 8.2 Open the file and dump trained model onto it

In [ ]:
with open('pickle_model','wb') as file:
    pickle.dump(lr_model, file) # source, destination

## 8.3 Load the saved Model using "Pickle object"

In [ ]:
with open('pickle_model','rb') as file:
    p_model = pickle.load(file)

# 9. Validate with trained and saved model

In [ ]:
p_model.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [ ]:
p_model.coef_

array([135.78767123])

In [ ]:
p_model.intercept_

180616.43835616432

# 10. Evaluate with trained and saved model

In [ ]:
p_model.score(df[['area']],df.price)

0.9584301138199486

# 11. Save Model To a File Using Sklearn's Joblib

It may be better to use **joblib** replacement of **_pickle (dump & load),_** which is more efficient on objects that carry **large numpy arrays** internally as is often the case for fitted __scikit-learn__ estimators,

In [ ]:
import joblib

In [ ]:
joblib.dump(model,'model_joblib') # source, destination

NameError: name 'model' is not defined

## Load the Saved Model using joblib

In [ ]:
j_model = joblib.load('model_joblib')

In [ ]:
j_model.predict([[5000]])

In [ ]:
j_model.intercept_

In [ ]:
j_model.coef_

In [ ]:
j_model.score(df[['area']],df.price)