# Matrix Types and Operations

In [1]:
from numpy import array
from numpy.linalg import inv

A = array([[1,2],[3,4],[5,6],[7,8]])
print(A)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Transpose
A defined matrix can be transposed, which creates a new matrix with the number of columns and rows flipped.

<br>This is denoted by the superscript **“T”** next to the matrix.
**C = A.T**</br>
We can transpose a matrix in NumPy by calling the **“T”** attribute.

In [2]:
C = A.T
print(C)

[[1 3 5 7]
 [2 4 6 8]]


In [6]:
A = array([[1.0,2.0],[3.0,4.0]])
I = inv(A)
print(A)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
