# Machine Learning Tutorial 12 - K Fold Cross Validation

Many times we get in a dilemma of which machine learning model should we use for a given problem. __KFold cross validation__ allows us to evaluate performance of a model by creating __K folds__ of given dataset. This is better then traditional __train_test_split.__ In this tutorial we will cover basics of __cross validation and kfold.__ We will also look into __cross_val_score__ function of __sklearn library__ which provides convenient way to run __cross validation on a model.__

Code: https://github.com/codebasics/py/blob/master/ML/12_KFold_Cross_Validation/12_k_fold.ipynb <br>
Credit: https://www.youtube.com/watch?v=gJo0uNL-5Qw&list=PLeo1K3hjS3uvCeTYTeyfe0-rN5r8zn9rw&index=13
#### Owner: Codebasics

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import numpy as np

#### By using <font color='maroon'>"sklearn", 'train_test_split'</font> method, load the digit dataset and then <font color='maroon'>"train, test, & split"</font> into "70% by 30%, respectively. 

In [25]:
from sklearn.model_selection import train_test_split
digits = load_digits()
#digits
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

#### Logistic Regression - LR
Use __Logistic Regression__ model to train and get the score of __digit dataset.__

In [26]:
lr = LogisticRegression(solver='liblinear', multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9518518518518518

#### Support Vector Machine - SVM

In [27]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.5462962962962963

#### Random Forest

In [28]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9666666666666667

### Load KFold cross validation libraries
#### Basic example

In [29]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [30]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


### 6. Define a function using KFold model for our digits example in order to train and get the score 

In [31]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

### 7. Use KFold to get score of all model by train & split

In [32]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [33]:
score_lr = []
score_svm = []
score_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    score_lr.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), \
                              X_train, X_test, y_train, y_test))  
    score_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [34]:
score_lr

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [35]:
score_rf

[0.9265442404006677, 0.9365609348914858, 0.9232053422370617]

In [36]:
score_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

### 8. cross_val_score function
Load __sklearn__ library, which will do all above task in single line of code.

In [37]:
from sklearn.model_selection import cross_val_score

### Logistic regression model performance using cross_val_score 

In [38]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target, cv=3)

array([0.89482471, 0.95325543, 0.90984975])

### svm model performance using cross_val_score 

In [39]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target, cv=3)

array([0.38063439, 0.41068447, 0.51252087])

### random forest performance using cross_val_score

In [40]:
cross_val_score(RandomForestClassifier(n_estimators=3), digits.data, digits.target, cv=3)

array([0.78964942, 0.8130217 , 0.80467446])

### 9. Parameter tunning using k fold cross validation

In [41]:
score1 = cross_val_score(RandomForestClassifier(), digits.data, digits.target,)
np.average(score1)

0.9354673475704116

In [42]:
score1 = cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target, cv=20)
np.average(score1)

0.9637702871410736