# 1. Definition
## 1.1. Description
A **Support Vector Machine (SVM)** is a supervised machine learning algorithm used for **classification and regression** tasks.
* The primary goal of an **SVM** is to find the *best boundary,* called a **hyperplane,** that separates different classes in the feature space

## 1.2 Key Concepts
**1. Hyperplane:**
In an SVM, the hyperplane is a decision boundary that separates the data points of different classes. In two-dimensional space, it's a line, but in higher dimensions, it becomes a plane or a hyperplane.

**2. Support Vectors:**
These are the data points that are closest to the hyperplane. They are critical in defining the position and orientation of the hyperplane. The support vectors are the most challenging cases and are used to maximize the margin of the classifier.

**3. Margin:**
This is the distance between the hyperplane and the nearest support vectors from either class. SVM aims to maximize this margin, providing the best separation between classes. A larger margin often leads to better generalization on unseen data.

## 1.3 Types of SVM
**1. Linear SVM:**
Used when the data is linearly separable, meaning it can be separated by a straight line (or hyperplane in higher dimensions).

**2. Non-linear SVM:**
Used when the data cannot be separated by a straight line. Non-linear SVMs use kernel functions to transform the data into a higher-dimensional space where a hyperplane can be used to separate the classes. Common kernel functions include:

* Polynomial Kernel
* Radial Basis Function (RBF) Kernel
* Sigmoid Kernel

# 2. Import libraries

In [ ]:
# import the necessary libraries required
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# 3. Load dataset

In [ ]:
# load the Iris flower dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

# 4. Split Dataset

In [ ]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 5. Feature scaling

In [ ]:
# it helps in speeding up the computations and achieving better performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 6. Create and train the SVM Model


In [ ]:
# Create an SVM classifier with a linear kernel
svm_classifier = SVC(kernel='linear')

# Train the model
svm_classifier.fit(X_train, y_train)

SVC(kernel='linear')

# 7. Make Predictions
Use the trained model to make predictions on the test set

In [ ]:
# Make predictions on the test set
y_pred = svm_classifier.predict(X_test)

# 8. Evaluate the Model
Evaluate the performance of the model using a confusion matrix and classification report

In [ ]:
# Print the confusion matrix
print("Confusion matrix =>\n", confusion_matrix(y_test, y_pred))

# Print the classification report
print("\nClassification report =>\n",classification_report(y_test, y_pred))

Confusion matrix =>
 [[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]

Classification report =>
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30

