# Machine Learning Tutorial Python - 5: Save Model Using Joblib And Pickle

Training machine learning model can be quite time consuming if training dataset is very big. In this case it makes sense to train a model and save it to a file so that later on while making predictions you can just load that model from a file and you don't need to train it every time. Pickle and sklearn joblib modules can be used for this purpose. Joblib seems to be more efficient with big numpy arrays hence it is preferred when you have many numpy objects involved in your training step.

Code: https://github.com/codebasics/py/blob...

Credit: https://www.youtube.com/watch?v=KfnhNlD8WZI&list=PLeo1K3hjS3uvCeTYTeyfe0-rN5r8zn9rw&t=0s

#### Owner: codebasics

# Save and load trained model using
1. pickle
2. sklearn joblib

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

### create data frame by loading csv file using "pandas"

In [3]:
df = pd.read_csv("homeprices.csv")
df

,area,price
0,2600,550000
1,3000,565000
2,3200,610000
3,3600,680000
4,4000,725000


### prepare and train the model

In [7]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

### predict the value from trained model

In [8]:
model.predict([[5000]])

C:\Users\39762\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [9]:
model.coef_

array([135.78767123])

In [10]:
model.intercept_

180616.43835616432

### Using linear regression to predict the house price
dependent variable = slope/coefficient * dependent variable + intercept<br>
y = m * x + b

In [11]:
135.78767123 * 5000 + 180616.43835616432

859554.7945061643

In [12]:
model.score(df[['area']], df['price'])

0.9584301138199486

## Let's use Pickle, to Save Model To a File Using Python Pickle.
Pickle is a module in Python used for serializing and de-serializing Python objects. This converts Python objects like lists, dictionaries, etc. into byte streams (zeroes and ones). You can convert the byte streams back into Python objects through a process called unpickling.

In [13]:
import pickle

In [14]:
with open('pickle_model','wb') as file:
    pickle.dump(model,file)

## Now, Load the Saved Model using Pickle 

In [16]:
with open('pickle_model','rb') as file:
    p_model = pickle.load(file)

In [17]:
p_model.predict([[5000]])

C:\Users\39762\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [18]:
p_model.coef_

array([135.78767123])

In [20]:
p_model.intercept_

180616.43835616432

In [22]:
p_model.score(df[['area']],df.price)

0.9584301138199486

## Save Trained Model Using joblib

In [23]:
import joblib

In [24]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [25]:
j_model = joblib.load('model_joblib')

In [26]:
j_model.predict([[5000]])

C:\Users\39762\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [27]:
j_model.intercept_

180616.43835616432

In [29]:
j_model.coef_

array([135.78767123])

In [30]:
j_model.score(j_model[['area']],j_model.price)

TypeError: 'LinearRegression' object is not subscriptable